Server:
  RunMOde: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
APP:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadBookAllowExts:
    - .txt

Database:
  DBType: sqlite3
  DBName: storage/library.db
  Username: root
  Password: 123456
  HKost: 127.0.0.1:3306  
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30